version: "3.7"

services:
  nginx:
    image: nginx:latest
    volumes:
      - /opt/www/html:/usr/share/nginx/html
      - /opt/www/conf.d:/etc/nginx/conf.d
    # ports:
    #   - "80:80"

networks:
  default:
    external:
      name: nginx_proxy_shared