version: '3.8'

services:
  # Docker 守护进程服务
  dind:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true  # dind 需要特权模式
    restart: unless-stopped
    networks:
      - jenkins-net
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - dind-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    command: --storage-driver overlay2

  # Jenkins 主服务器
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    networks:
      - jenkins-net
    environment:
      - DOCKER_HOST=tcp://dind:2376
      - DOCKER_CERT_PATH=/var/jenkins_home/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - dind-certs:/var/jenkins_home/certs/client:ro
    ports:
      - "8080:8080"
      - "50000:50000"
    depends_on:
      - dind

networks:
  jenkins-net:
    driver: bridge

volumes:
  dind-certs:
  jenkins-data: