version: "3.8"

services:
  cloudreve:
    container_name: cloudreve
    image: cloudreve/cloudreve:latest
    restart: unless-stopped
    # ports:
    #   - "5212:5212"
    volumes:
      - temp_data:/data
      - /opt/cloudreve/uploads:/cloudreve/uploads
      - /opt/cloudreve/conf.ini:/cloudreve/conf.ini
      - /opt/cloudreve/cloudreve.db:/cloudreve/cloudreve.db
      - /opt/cloudreve/avatar:/cloudreve/avatar
    depends_on:
      - aria2

  aria2:
    container_name: aria2
    image: p3terx/aria2-pro
    restart: unless-stopped
    environment:
      - RPC_SECRET=secret
      - RPC_PORT=6800
    volumes:
      - /opt/cloudreve/aria2_config/:/config
      - temp_data:/data

volumes:
  temp_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/cloudreve/data/
      o: bind