services:
  beszel:
    image: 'henrygd/beszel'
    container_name: 'beszel'
    restart: unless-stopped
    # ports:
    #   - '8090:8090'
    volumes:
      - /opt/beszel_data:/beszel_data
    networks:
      nginx_proxy_shared:
      beszel:
        ipv4_address: 172.26.0.6

  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk1/.beszel:/extra-filesystems/disk1:ro
    environment:
      PORT: 45876
      KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP6ynksKwqR93KDbZ5pNkfyhye5DSDAj4GpcJHXTbwjn"
      # FILESYSTEM: /dev/sda1 # override the root partition / device for disk I/O stats
    networks:
      nginx_proxy_shared:
      beszel:
        ipv4_address: 172.26.0.5

networks:
  nginx_proxy_shared:
    name: nginx_proxy_shared
    external: true
  beszel:
    name: beszel
    external: true