version: '3.8'

services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    # ports:
    #   - "5000:80"

networks:
  default:
    external:
      name: nginx_proxy_shared